#!/bin/bash
echo "Hello and Good afternoon"
echo "And Welcome to the session"
echo "Hello and Good afternoon"
echo "And Welcome to the session"echo "Hello and Good afternoon"
echo "And Welcome to the session"echo "Hello and Good afternoon"
echo "And Welcome to the session"echo "Hello and Good afternoon"
echo "And Welcome to the session"
echo "Hello and Good afternoon"
echo "And Welcome to the session"
